apiVersion: v1
kind: Namespace
metadata:
  name: applications
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/part-of: primaza
  name: primaza-app-agent
  namespace: applications
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: primaza:app:leader-election
  namespace: applications
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: primaza:app:manager
  namespace: applications
rules:
- apiGroups:
  - primaza.io
  resources:
  - servicebindings
  - serviceclaims
  - servicecatalogs
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - primaza.io
  resources:
  - serviceclaims/status
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - primaza.io
  resources:
  - servicebindings/status
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - apps
  resourceNames:
  - primaza-app-agent
  resources:
  - deployments
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
  - watch
  - update
- apiGroups:
  - primaza.io
  resources:
  - servicebindings/finalizers
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/part-of: primaza
  name: primaza:app:leader-election
  namespace: applications
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: primaza:app:leader-election
subjects:
- kind: ServiceAccount
  name: primaza-app-agent
  namespace: applications
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/part-of: primaza
  name: primaza:app:manager
  namespace: applications
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: primaza:app:manager
subjects:
- kind: ServiceAccount
  name: primaza-app-agent
  namespace: applications
