apiVersion: sqs.services.k8s.aws/v1alpha1
kind: Queue
metadata:
  name: sqs-orders-prod
  namespace: services-prod
spec:
  queueName: orders-prod
  tags:
    env: prod
    project: demo-app
    scope: primaza-ephemeral-demo
